- name: U-06. check "." in profile
  command: grep ^PATH {{ profile_path }}
  register: result
  changed_when: "'.' in result.stdout"
  failed_when: result.rc | int > 1
- debug:
    var: result.stdout
  when: "'.' in result.stdout"

- debug:
    msg: "No configure 'PATH' in {{ profile_path }}"
  when: result.rc == 1

- name: U-06. remove "." if "." exist in profile
  block:
  - shell: grep ^PATH {{ profile_path }} | tr -d '.' | tr -s ':/' 
    register: remove
  - debug:
      var: remove.stdout

  - replace:
      path: "{{ profile_path }}"
      regexp: PATH.*
      replace: "{{ remove.stdout }}"
    register: replace
  - debug:
      var: replace
  when: "'.' in result.stdout" 
