- name: U-05. Password file protection
  block:
  - name: U-05. check /etc/passwd second field is x
    shell: awk -F ':' '{ print $2 }' /etc/passwd | uniq
    register: result
    failed_when: result.stdout != "x"
    changed_when: result.stdout != "x"
  - debug:
      msg: "second field is {{ result.stdout }}"

  rescue:
  - name: U-05. execute pwconv if second field isn't "x"
    shell: pwconv
