---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
  - name: U-02. Set password complexity in RHEL affiliation
    pamd:
      name: system-auth
      type: password
      control: requisite 
      module_path: pam_pwquality.so
      state: updated # default
      module_arguments: try_first_pass local_users_only enforce_for_root retry=3 authtok_type= minlen=8 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 
    when: ansible_distribution == "CentOS"

  - name: U-02. Set password complexity in Debian affiliation
    pamd:
      name: common-password
      type: password
      control: requisite 
      module_path: pam_pwquality.so
      state: updated # default
      module_arguments: enforce_for_root retry=3 minlen=8 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 
    when: ansible_distribution == "Ubuntu"
