---
- hosts: localhost
  become: yes

  tasks:
  - name: Password file protection
    block:
    - name: check /etc/passwd second field is x
      shell: awk -F ':' '{ print $2 }' /etc/passwd | uniq
      register: result
      failed_when: result.stdout != "x"
      changed_when: result.stdout != "x"
    - debug:
        msg: "second field is {{ result.stdout }}"

    rescue:
    - name: execute pwconv if second field isn't "x"
      shell: pwconv
