---
- hosts: localhost
  become: yes

  tasks:
  - name: check permission and owner /etc/passwd
    stat:
      path: /etc/passwd
    register: stat

  - name: change permission and owner /etc/passwd
    file:
      path: /etc/passwd
      owner: root
      group: root
      mode: '0644'
    when: stat.stat.pw_name != 'root' or stat.stat.gr_name != 'root' or stat.stat.mode | int > 644
