---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: check permission and owner /etc/hosts
    stat:
      path: /etc/hosts
    register: stat

  - name: change permission and owner /etc/hosts
    file:
      path: /etc/hosts
      owner: root
      group: root
      mode: '0644'
    when: stat.stat.pw_name != 'root' or stat.stat.gr_name != 'root' or stat.stat.mode > 644
